# VUT FIT MITAI
# PRL 2019/2020
# Project 2: Odd-even transposition sort algorithm
# Author: Vladimir Dusek
# Login: xdusek27

zip:
	cp doc/doc.pdf ./xdusek27.pdf ; zip xdusek27.zip ots.cpp test.sh xdusek27.pdf ; rm xdusek27.pdf

clean:
	rm -f xdusek27.pdf xdusek27.zip
