# VUT FIT
# IZP 2016/2017
# Projekt 1 - Prace s textem
# Soubor: Makefile
# Autor: Vladimir Dusek, xdusek27 (1BIT)
# Datum: 6. 11. 2016

CC = gcc
CFLAGS = -std=c99 -Wall -Wextra -Werror
NAME = proj1

all: proj1.c
	$(CC) $(CFLAGS) $(NAME).c -o $(NAME)
