# VUT FIT MITAI
# PRL 2019/2020
# Project 3: Viditelnost
# Author: Vladimir Dusek
# Login: xdusek27

zip:
	cp doc/doc.pdf ./xdusek27.pdf ; \
	zip xdusek27.zip vid.cpp test.sh xdusek27.pdf ; \
	rm -f xdusek27.pdf

clean:
	rm -f xdusek27.pdf xdusek27.zip vid
