# VUT FIT
# IZP 2016/2017
# Projekt 2 - Iteracni vypocty
# Soubor: Makefile
# Autor: Vladimir Dusek, xdusek27 (1BIT)
# Datum: 27. 11. 2016

CC = gcc
CFLAGS = -std=c99 -Wall -Wextra -Werror
NAME = proj2

all: proj2.c
	$(CC) $(CFLAGS) $(NAME).c -lm -o $(NAME)
