version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
    networks:
      - belk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - belk
    depends_on:
      - elasticsearch

  packetbeat:
    image: packetbeat:latest
    container_name: packetbeat
    restart: always
    build:
      context: ./
      dockerfile: Packetbeat.Dockerfile
    cap_add:
      - NET_ADMIN
    networks:
      - belk
    depends_on:
      - kibana

volumes:
  data:
    driver: local

networks:
  belk:
    driver: bridge
