# Packetbeat reference configuration file:
#   - https://www.elastic.co/guide/en/beats/packetbeat/master/packetbeat-reference-yml.html

packetbeat.interfaces.device: eth0

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
  - type: icmp
    enabled: true

  - type: dhcpv4
    enabled: true
    ports: [67, 68]

  - type: dns
    enabled: true
    ports: [53]
    include_authorities: true
    include_additionals: true

  - type: http
    enabled: true
    ports: [80, 8080, 8000, 5000, 8002]

  - type: tls
    enabled: true
    ports: [443, 993, 995, 5223, 8443, 8883, 9243]
    fingerprints: [md5, sha1, sha256]
    send_certificates: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.dashboards.enabled: true

setup.kibana:
  host: "kibana:5601"
