[package]
name = "kry-1"
version = "0.1.0"
authors = ["Vladimír Dušek <v.dusek96@@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
