# Generated by Django 2.1.2 on 2018-12-03 10:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('date_time', models.DateTimeField(null=True, unique=True)),
                ('played', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveSmallIntegerField(choices=[(2, '2 minutes'), (5, '5 minutes')], null=True)),
                ('time', models.TimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Match')),
            ],
            options={
                'verbose_name_plural': 'Penalties',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defender'), ('A', 'Attacker')], max_length=1, null=True)),
                ('dress_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('type', models.CharField(choices=[('GP', 'Group phase'), ('EF', 'Eight-final'), ('QF', 'Quaterfinal'), ('SF', 'Semifinal'), ('F', 'Final')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(null=True, unique=True)),
                ('end_date', models.DateField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registered', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Season')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='seasonteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Team'),
        ),
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(through='browser.SeasonTeam', to='browser.Team'),
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Season'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_season',
            field=models.ManyToManyField(related_name='teams', to='browser.SeasonTeam'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_away_team', to='browser.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_players',
            field=models.ManyToManyField(related_name='away_team_players', to='browser.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='browser.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_players',
            field=models.ManyToManyField(related_name='home_team_players', to='browser.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Round'),
        ),
        migrations.AddField(
            model_name='goal',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_assist_player', to='browser.Player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='collect_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_collect_team', to='browser.Team'),
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Match'),
        ),
        migrations.AddField(
            model_name='goal',
            name='score_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_score_player', to='browser.Player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='score_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_score_team', to='browser.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonteam',
            unique_together={('team', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('number', 'season')},
        ),
    ]
